# Generated by Django 4.2.5 on 2023-09-09 22:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('old_site', models.CharField(max_length=200)),
                ('orientation', models.TextField()),
                ('trading', models.TextField()),
                ('advantages', models.TextField()),
                ('competitors', models.TextField()),
                ('customers', models.TextField()),
                ('locations', models.TextField()),
                ('trade_object', models.TextField()),
                ('goods_quantity', models.CharField(choices=[('100', '100'), ('1000', '1000'), ('10000', '10000'), ('100000', '100000'), ('500', '500'), ('другое', 'другое')], default='100', max_length=200)),
                ('category_quantity', models.TextField()),
                ('characters_item', models.TextField()),
                ('money', models.CharField(choices=[('Доллары', 'Доллары'), ('Другое', 'Другое'), ('Евро', 'Евро'), ('Рубли', 'Рубли')], default='Рубли', max_length=200)),
                ('Setup_exchange_rate', models.CharField(choices=[('Автоматически', 'Автоматически'), ('Вручную', 'Вручную'), ('Другое', 'Другое')], default='Вручную', max_length=200)),
                ('price_type', models.TextField()),
                ('discount_type', models.CharField(choices=[('Другое', 'Другое'), ('На группы товаров', 'На группы товаров'), ('Накопительные скидки', 'Накопительные скидки'), ('По группам пользователей', 'По группам пользователей'), ('Промокоды', 'Промокоды'), ('Скидки от суммы заказа', 'Скидки от суммы заказа')], default='По группам пользователей', max_length=200)),
                ('registration_need', models.CharField(choices=[('Другое', 'Другое'), ('Нет, достаточно корзины для незарегистрированного пользователя', 'Нет, достаточно корзины для незарегистрированного пользователя'), ('Регистрация по e-mail', 'Регистрация по e-mail'), ('Регистрация по sms', 'Регистрация по sms')], default='Регистрация по e-mail', max_length=200)),
                ('pay_type', models.CharField(choices=[('Другое', 'Другое'), ('Квитанция', 'Квитанция'), ('Наличным курьеру', 'Наличным курьеру'), ('Онлайн-оплата', 'Онлайн-оплата'), ('По счету', 'По счету')], default='Онлайн-оплата', max_length=200)),
                ('type_delievery', models.CharField(choices=[('Другое', 'Другое'), ('Самовывоз', 'Самовывоз'), ('Свои пункты выдачи', 'Свои пункты выдачи'), ('Транспортная компания', 'Транспортная компания')], default='Транспортная компания', max_length=200)),
                ('order_priem', models.CharField(choices=[('Другое', 'Другое'), ('Заказы поступают на email менеджера и вся дальнейшая обработка заказов ведется в оффлайн режиме', 'Заказы поступают на email менеджера и вся дальнейшая обработка заказов ведется в оффлайн режиме'), ('Интеграция с другими системами', 'Интеграция с другими системами'), ('На email менеджера поступает уведомление, а обработка заказов ведется на сайте ', 'На email менеджера поступает уведомление, а обработка заказов ведется на сайте ')], max_length=200)),
                ('utochnenie', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Новости\\Блог'), ('2', 'Контактная информация'), ('3', 'Интерактивная карта проезда'), ('4', 'Статьи (полезная информация)'), ('5', 'Индивидуальные параметры товаров для каждой группы (длина, ширина, высота и тд)'), ('6', 'Онлайн-оплата товаров'), ('7', 'Корзина покупок'), ('8', 'Сравнение товаров в интернет-магазине'), ('9', 'WishList (Список желаний)'), ('10', 'Поиск по сайту'), ('11', 'Поиск товаров по параметрам'), ('12', 'Акции'), ('13', 'Скидки'), ('14', 'Банеры'), ('15', 'Партнеры'), ('16', 'Онлайн-консультант'), ('17', 'Онлайн-заявки и формы заказа с сайта'), ('18', 'Интеграция сайта с социальными сетями'), ('19', 'Геопривязка к городам'), ('20', 'Онлайн-формирование документов (счетов для оплаты и прочее)'), ('21', 'Печать чеков')], max_length=255)),
                ('design', multiselectfield.db.fields.MultiSelectField(choices=[('Другое', 'Другое'), ('Логотип', 'Логотип'), ('Фирменный стиль, брэндбук', 'Фирменный стиль, брэндбук'), ('Фото, видео, другое', 'Фото, видео, другое'), ('Цветовая гамма', 'Цветовая гамма')], max_length=255)),
                ('good_examples', models.TextField()),
                ('bad_examples', models.TextField()),
                ('additional_wishes', models.TextField()),
                ('wish_work_hours', models.TextField()),
                ('files', models.FileField(upload_to='files/')),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
