# Generated by Django 4.2.5 on 2023-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerce',
            name='soglasie',
            field=models.BooleanField(default=False),
        ),
    ]
